source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.1'
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'rack-cors', require: 'rack/cors'
gem 'bcrypt', '~> 3.1.12', platforms: [:ruby, :x64_mingw, :mingw]
gem 'pagy'
gem 'has_scope', '~> 0.7.2'


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
